id: IB3824773
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:12:52+00:00'
last_modified: '2022-06-07T13:35:14.392172+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21598
  title: བུད་མེད་བདེ་སྲུང་སྐོར་གྱི་རྒྱུན་ཤེས་ཕྲན་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4700':
      image_group_id: I1KG21705
      title: ''
      total_pages: 146
      order: 1
      base_file: 4700.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
